### PR TITLE
issue #1 bug: not scrolling tasks on home screen

### LINKED ISSUE #1: bug: not scrolling tasks on home screen

### PR DESCRIPTION
**Pull request by kitkat0225**
update scrollview and container flex property
close #1

### CODE REVIEW

File: scenes/Home.js [hunk 1]
```diff
@@ -44,6 +44,7 @@ const Home = ({ navigation }) => {
                         ><Text style={styles.button}>Remove</Text></TouchableOpacity>
                     </View>
                 )}
+                style = {{ flex: 1 }}
```
Comment (kitkat0225) [inline scenes/Home.js:47]: style={{  flex: 1 }}
